eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://eurekaserviceregistry-dev:8761/eureka/

spring:
  datasource:
    url: jdbc:postgresql://fightcluckservice-dev-postgresql:5432/fightcluckservice-dev
    username: fightcluckservice-dev
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

server:
  port: 8001

logging:
  level:
    root: info
    org.hibernate.SQL: debug
    com.netflix: debug
    org.springframework.cloud: info
    org.springframework.web: debug
    org.springframework.sql: debug
    com.stoi: debug