spring.application.name=fightcluckservice
server.port=8001

spring.config.import=optional:configserver:

#eureka.client.enabled=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

management.tracing.sampling.probability=1.0
#logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]