eureka:
  #  dashboard:
  #    path: /eurekawebui
  instance:
    hostname: localhost
    non-secure-port: 7761
  client:
    enabled: true
    server:
      waitTimeInMsWhenSyncEmpty: 0
    service-url:
#      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.non-secure-port}/eureka
      defaultZone: http://${login.admin.user}:${login.admin.password}@${eureka.instance.hostname}:${eureka.instance.non-secure-port}/eureka

spring:
  datasource:
    url: jdbc:postgresql://localhost:8431/fightcluckservice-dev
    username: fightcluckservice-dev
  jpa:
    hibernate:
      ddl-auto: create-drop

spring.cloud:
  config:
    username: ${login.admin.user}
    password: ${login.admin.password}

server:
  port: 7001

logging:
  level:
    root: info
#    org.springframework.web: info
#    org.springframework.web.servlet.mvc.method.annotation: trace
    com.netflix.discovery.shared.transport.jersey3: trace
    com.stoi: debug