application.version: 1.0B

login:
  eureka:
    user: EUREKA
    password: ADMIN
  admin:
    user: admin
    password: admin

springdoc:
  show-spring-cloud-functions: true
  show-actuator: false
  swagger-ui:
    enabled=true:
    path: /admin/swagger-ui
  api-docs:
    #    path: /api-docs
    groups.enabled: true

spring:
  application:
    name: fightcluckservice
    instance-id: ${spring.application.name}:${random.uuid}
  config:
    import: "optional:configserver:"
  jackson:
    serialization:
      indent-output: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    password:
    hikari:
      poolName: Hikari
  jpa:
    database: POSTGRESQL
  output.ansi.enabled: always

eureka:
  instance:
    health-check-url-path: /actuator/health
    instance-id: ${spring.application.name}:${random.uuid}
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 5
    prefer-ip-address: true
    metadata-map:
      startup: ${random.int}
      zone: primary # This is needed for the load balancer
  client:
    enabled: true
    fetch-registry: true
    register-with-eureka: true
    initial-instance-info-replication-interval-seconds: 5
    instance-info-replication-interval-seconds: 10
    registry-fetch-interval-seconds: 10
    healthcheck.enabled: true
    server.waitTimeInMsWhenSyncEmpty: 0

management:
  info:
    env.enabled: true
    git:
      mode: full
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
    env:
      keys-to-sanitize: password,secret
      show-values: always
    configprops:
      show-values: always
  endpoint:
    enabled-by-default: true
    refresh.enabled: true
    restart.enabled: false
    shutdown.enabled: true
    info:
      enabled: true
      show-values: ALWAYS
    env:
      keys-to-sanitize: password,secret
      show-values: always
      post.enabled: true
    health.show-details: always
    configprops.show-values: always

logging:
  pattern:
    console: "%black(%d{ISO8601}) %highlight(%-5level) %yellow(%c{2}): %msg%n%throwable"
#    file: "%black(%d{ISO8601}) %highlight(%-5level) %yellow(%c{2}): %msg%n%throwable"