eureka:
  #  dashboard:
  #    path: /eurekawebui
  instance:
    hostname: localhost
    non-secure-port: 8761
  client:
    enabled: true
    server:
      waitTimeInMsWhenSyncEmpty: 0
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.non-secure-port}/eureka
#      defaultZone: http://${login.eureka.user}:${login.eureka.password}@${eureka.instance.hostname}:${eureka.instance.non-secure-port}/eureka

spring:
  datasource:
    url: jdbc:postgresql://localhost:8431/fightcluckservice-dev
    username: fightcluckservice-dev
  jpa:
    hibernate:
      ddl-auto: create-drop

server:
  port: 7001

logging:
  level:
    root: info
    org.springframework.web: error
    com.stoi: debug