application.version: 1.0B

spring:
  application:
    name: fightcluckservice
  config:
    import: "optional:configserver:"
  jackson:
    serialization:
      indent-output: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    password:
    hikari:
      poolName: Hikari
  jpa:
    database: POSTGRESQL

#logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]