eureka:
  #  dashboard:
  #    path: /eurekawebui
  instance:
    hostname: eurekaserviceregistry-dev
    non-secure-port: 8761
  client:
    enabled: true
    server:
      waitTimeInMsWhenSyncEmpty: 0
    service-url:
      defaultZone: http://${login.admin.user}:${login.admin.password}@${eureka.instance.hostname}:${eureka.instance.non-secure-port}/eureka

spring:
  datasource:
    url: jdbc:postgresql://fightcluckservice-dev-postgresql:5432/fightcluckservice-dev
    username: fightcluckservice-dev
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

server:
  port: 8001

logging:
  level:
    root: info
    org.hibernate.SQL: debug
    com.netflix: debug
    org.springframework.cloud: info
    org.springframework.web: debug
    org.springframework.sql: debug
    com.stoi: debug