eureka:
  #  dashboard:
  #    path: /eurekawebui
  instance:
    hostname: eurekaserviceregistry-prod
    non-secure-port: 9761
  client:
    enabled: true
    server:
      waitTimeInMsWhenSyncEmpty: 0
    service-url:
      defaultZone: http://${login.admin.user}:${login.admin.password}@${eureka.instance.hostname}:${eureka.instance.non-secure-port}/eureka

spring:
  datasource:
    url: jdbc:postgresql://fightcluckservice-prod-postgresql:5432/fightcluckservice-prod
    username: fightcluckservice-prod
  jpa:
    hibernate:
      ddl-auto: none

server:
  port: 9001

logging:
  level:
    root: info
    org.springframework.web: error
    com.stoi: debug