eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://naming-server-prod-app:9761/eureka/

spring:
  datasource:
    url: jdbc:postgresql://fightcluckservice-prod-postgresql:5432/fightcluckservice-prod
    username: fightcluckservice-prod
  jpa:
    hibernate:
      ddl-auto: none

server:
  port: 9001

logging:
  level:
    root: info
    org.springframework.web: error
    com.stoi: debug