# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
version: '3.8'

services:
  fightcluckservice-dev-postgresql:
    image: postgres:13.2
    ports:
      - 127.0.0.1:8431:5432
    networks:
      - fightcluck-network-dev
    volumes:
      - ~/volumes/s2i/fightcluckservice-dev/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=fightcluckservice-dev
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust

  eurekaserviceregistry-dev:
    image: eurekaserviceregistry
    ports:
      - 127.0.0.1:8761:8761
    networks:
      - fightcluck-network-dev
    environment:
      #      server.port: 8761
      APP_DELAY_STARTUP: 0
      SPRING_PROFILES_ACTIVE: dev
      _JAVA_OPTIONS: -Xmx512m -Xms256m

  fightcluckservice-dev-app:
    image: fightcluckservice
    ports:
      - 127.0.0.1:8001:8001
    networks:
      - fightcluck-network-dev
    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://fightcluckservice-dev-postgresql:5432/fightcluckservice-dev
#      server.port: 8001
#      eureka.client.service-url.defaultZone: http://admin:admin@eurekaserviceregistry-dev:8761/eureka
      APP_DELAY_STARTUP: 10
#      _JAVA_OPTIONS: -Xmx512m -Xms256m -Dspring.profiles.active=prod,api-docs,static
      _JAVA_OPTIONS: -Xmx512m -Xms256m
      SPRING_PROFILES_ACTIVE: dev
    depends_on:
      - fightcluckservice-dev-postgresql
      - eurekaserviceregistry-dev

networks:
  fightcluck-network-dev:
    name: fightcluck-network-dev
    driver: bridge
    external: true