# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
version: '3.8'

services:
  fightcluckservice-dev-postgresql:
    image: postgres:13.2
    ports:
      - 127.0.0.1:5431:5432
    networks:
      - fightcluck-network
    volumes:
      - ~/volumes/s2i/fightcluckservice-dev/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=fightcluckservice-dev
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust

  fightcluckservice-prod-postgresql:
    image: postgres:13.2
    ports:
      - 127.0.0.1:5430:5432
    networks:
      - fightcluck-network
    volumes:
      - ~/volumes/s2i/fightcluckservice-prod/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=fightcluckservice-prod
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust

  naming-server-dev-app:
    image: namingserver
    ports:
      - 127.0.0.1:8761:8761
    networks:
      - fightcluck-network
    environment:
#      server.port: 8761
      eureka.client.register-with-eureka: false
      eureka.client.fetch-registry: false
    depends_on:
      - fightcluckservice-dev-postgresql

  fightcluckservice-app:
    image: fightcluckservice
    ports:
      - 127.0.0.1:8001:8001
    networks:
      - fightcluck-network
    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://fightcluckservice-dev-postgresql:5432/fightcluckservice-dev
#      server.port: 8001
#      eureka.client.service-url.defaultZone: http://naming-server-dev-app:8761/eureka/
      APP_DELAY_STARTUP: 10
#      _JAVA_OPTIONS: -Xmx512m -Xms256m -Dspring.profiles.active=prod,api-docs,static
      _JAVA_OPTIONS: -Xmx512m -Xms256m
      SPRING_PROFILES_ACTIVE: prod
    depends_on:
      - fightcluckservice-dev-postgresql
      - naming-server-dev-app

networks:
  fightcluck-network:
    name: fightcluck-network
    driver: bridge
    external: true