# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
version: '3.8'
services:
  fightcluckservice-dev-postgresql:
    image: postgres:13.2
    ports:
      - 127.0.0.1:8431:5432
    networks:
      - fightcluck-network-dev
    volumes:
      - ~/volumes/s2i/fightcluckservice-dev/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=fightcluckservice-dev
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust

  fightcluckservice-prod-postgresql:
    image: postgres:13.2
    ports:
      - 127.0.0.1:9430:5432
    networks:
      - fightcluck-network-prod
    volumes:
      - ~/volumes/s2i/fightcluckservice-prod/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=fightcluckservice-prod
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust

networks:
  fightcluck-network-dev:
    name: fightcluck-network-dev
    driver: bridge
    external: true
  fightcluck-network-prod:
    name: fightcluck-network-prod
    driver: bridge
    external: true